# Generated by Django 5.2.7 on 2025-11-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0011_paymentrequest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='is_super_officer',
            field=models.BooleanField(default=False, help_text='Can access admin data for all students under this organization', verbose_name='Super Officer'),
        ),
    ]
