# Generated by Django 5.2.7 on 2025-11-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0012_add_is_super_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='can_promote_officers',
            field=models.BooleanField(default=False, help_text='Allow this officer to promote students to officers and grant promotion permissions', verbose_name='Can Promote Officers'),
        ),
        migrations.AddField(
            model_name='organization',
            name='hierarchy_level',
            field=models.CharField(choices=[('COLLEGE', 'College Level'), ('PROGRAM', 'Program Level'), ('CLUB', 'Club/Organization Level')], default='PROGRAM', help_text='Indicates the hierarchical level (College, Program, or Club)', max_length=20, verbose_name='Organization Level'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, help_text='For programs: set to their parent college. Null for college-level organizations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_organizations', to='paymentorg.organization', verbose_name='Parent Organization'),
        ),
    ]
