# Generated by Django 5.2.7 on 2025-11-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0013_officer_can_promote_officers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='can_create_officers',
            field=models.BooleanField(default=False, help_text='Allow this officer to create new officer accounts from scratch (ALLORG privilege)', verbose_name='Can Create Officers'),
        ),
    ]
