# Generated by Django 5.2.7 on 2025-11-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0014_add_can_create_officers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officer',
            options={'ordering': ['organization', 'user__last_name'], 'verbose_name': 'Officer', 'verbose_name_plural': 'Officers'},
        ),
        migrations.RemoveField(
            model_name='officer',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='last_name',
        ),
    ]
