# Generated by Django 5.2.7 on 2025-11-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0015_alter_officer_options_remove_officer_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='phone_number',
        ),
    ]
