# Generated by Django 5.2.7 on 2025-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentorg', '0016_remove_officer_email_remove_officer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='can_create_officers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: 09XX-XXX-XXXX', max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
